# Generated by Django 3.1.7 on 2021-04-16 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=60)),
                ('ISBN', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Language', models.CharField(max_length=60)),
                ('Publisher', models.CharField(max_length=60)),
                ('CategoryType', models.CharField(choices=[('NEW', 'New'), ('RENT', 'Rent'), ('MOE', 'MOE')], max_length=4)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('CategoryName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('FName', models.CharField(blank=True, max_length=60, null=True)),
                ('LName', models.CharField(blank=True, max_length=60, null=True)),
                ('ContactNo', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('University', models.CharField(blank=True, max_length=255, null=True)),
                ('Major', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsedBook',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('Book_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Book_Title', models.CharField(max_length=60)),
                ('Book_Price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kitaby.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(to='Kitaby.OrderBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
