# Generated by Django 3.1.7 on 2021-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=60)),
                ('ISBN', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Language', models.CharField(max_length=60)),
                ('Publisher', models.CharField(max_length=60)),
            ],
        ),
    ]
