# Generated by Django 3.1.7 on 2021-03-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedBook',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=60)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
