# Generated by Django 3.1.7 on 2021-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
