# Generated by Django 3.1.7 on 2021-04-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0002_auto_20210404_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='University',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
