# Generated by Django 3.1.7 on 2021-03-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0002_usedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('CategoryName', models.CharField(max_length=60)),
            ],
        ),
    ]
