# Generated by Django 3.1.7 on 2021-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0003_auto_20210404_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedbook',
            old_name='Price',
            new_name='Book_Price',
        ),
        migrations.RenameField(
            model_name='usedbook',
            old_name='Title',
            new_name='Book_Title',
        ),
        migrations.AlterField(
            model_name='usedbook',
            name='BookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
