# Generated by Django 3.1.7 on 2021-04-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0005_order_orderbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='CategoryType',
            field=models.CharField(choices=[('NEW', 'New'), ('RENT', 'Rent'), ('MOE', 'MOE')], default='NEW', max_length=4),
            preserve_default=False,
        ),
    ]
