# Generated by Django 3.1.7 on 2021-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0006_book_categorytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedbook',
            name='Book_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
