# Generated by Django 3.1.7 on 2021-04-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0007_usedbook_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='test-book'),
            preserve_default=False,
        ),
    ]
