# Generated by Django 3.1.7 on 2021-04-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0008_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
