# Generated by Django 3.1.7 on 2021-04-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0009_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
