# Generated by Django 3.1.7 on 2021-04-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0010_auto_20210413_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_date',
            field=models.DateTimeField(),
        ),
    ]
