# Generated by Django 3.1.7 on 2021-04-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0011_auto_20210413_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_date',
            new_name='ordered_date',
        ),
    ]
