# Generated by Django 3.1.7 on 2021-04-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaby', '0013_auto_20210413_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kitaby.user'),
        ),
    ]
